### ISSUE TITLE
Remove Hardcoded DB Credentials

### ISSUE THREAD

**Issue by aryker** [frc868/Scouting-System-2017#2]
The database credentials are hardcoded in the PHP code, which is visible by anyone with access to our Git repository. We need to come up with an alternate system so that our passwords are not leaked to the public.

**Comment by karagenit** [comment]
#### Files

- sql.php
- getTeam.php
- pit.php

Let me know if you can see any others.

**Comment by karagenit** [comment]
Follow up: might be a good idea to remove the MySQL username & the database name.

**Comment by karagenit** [comment]
Alright, it's done, passwords are removed. If anyone ever tries to host this they'll need the `.db-password` file with the password in it (we should probably make a setup script for that).
